export type MessageRole = 'user' | 'assistant' | 'system';

export interface TextContent {
  type: 'text';
  text: string;
  parentToolUseId?: string;
}

export interface ToolUseContent {
  type: 'tool_use';
  id: string;
  name: string;
  input: Record<string, unknown>;
  parentToolUseId?: string;
  /**
   * Raw accumulated partial-JSON of the tool input while it streams. The API
   * sends the input as a series of `input_json_delta` fragments that must be
   * concatenated and parsed once (on `content_block_stop`) — a single fragment
   * is not valid JSON on its own. Transient; cleared once parsed into `input`.
   */
  inputJson?: string;
  /**
   * Lifecycle for TUI-parity rendering: 'running' from the tool_use block start
   * until its tool_result arrives, then 'done' or 'error'. Mirrors how Claude
   * Code's TUI shows a running indicator and then the result/diff.
   */
  status?: 'running' | 'done' | 'error';
}

export interface ToolResultContent {
  type: 'tool_result';
  tool_use_id: string;
  content: string;
  is_error?: boolean;
}

export interface ThinkingContent {
  type: 'thinking';
  thinking: string;
  parentToolUseId?: string;
}

export interface ImageContent {
  type: 'image';
  source: {
    type: 'base64' | 'url';
    media_type: string; // e.g., 'image/png', 'image/jpeg'
    data?: string; // base64-encoded image data
    url?: string; // image URL
  };
}

/** A mid-stream nudge/feedback injected by the user while the agent is running */
export interface NudgeContent {
  type: 'nudge';
  text: string;
}

/** A message received from another agent in a different conversation/session */
export interface CrossSessionContent {
  type: 'cross_session';
  text: string;
  fromConversationId: string;
  fromConversationTitle: string;
  fromWorkspaceName: string;
  fromAgentProfile?: string;
  messageId: string;
}

export type MessageContent =
  | TextContent
  | ToolUseContent
  | ToolResultContent
  | ThinkingContent
  | ImageContent
  | NudgeContent
  | CrossSessionContent;

export interface Message {
  id: string;
  role: MessageRole;
  content: MessageContent[];
  timestamp: number;
  model?: string;
  tokenCount?: number;
  // For tool calls, track approval state
  toolApprovals?: Record<string, ToolApprovalState>;
  // Voice metadata
  isVoiceMessage?: boolean;
  /** Handle of the @-mentioned agent that produced this message, if any.
   *  e.g. 'claude-code'. Client renders a chip on the bubble. */
  agentHandle?: string;
}

export type ToolApprovalState = 'pending' | 'approved' | 'denied';

export interface Conversation {
  id: string;
  title: string;
  messages: Message[];
  createdAt: number;
  updatedAt: number;
  model: string;
  systemPrompt?: string;
  workspacePath?: string;
  workspaceId?: string;
  totalTokens: number;
  maxContextTokens: number;
  // Plan mode
  planMode: boolean;
  planFile?: string;
  // Memory
  memoryFiles: string[];
  // CLI parity settings
  permissionMode?: string;
  effort?: string;
  maxBudgetUsd?: number;
  maxTurns?: number;
  allowedTools?: string[];
  disallowedTools?: string[];
  cliSessionId?: string;
  /** ID of the parent conversation this was forked from */
  parentConversationId?: string;
  /** ID of the message in the parent where the fork occurred */
  forkedFromMessageId?: string;
}

export interface ConversationSummary {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  messageCount: number;
  model: string;
  workspacePath?: string;
  workspaceId?: string;
  /** Stored compact summary text (generated by LLM during compaction or on-demand) */
  compactSummary?: string;
  /** ID of the parent conversation this was forked from */
  parentConversationId?: string;
  /** ID of the message in the parent where the fork occurred */
  forkedFromMessageId?: string;
}
